---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: vedaos
description: Opinionated custom image with GNOME, preinstalled Steam and other goodies, based on fedora-bootc.
base-image: quay.io/fedora/fedora-bootc
image-version: 43

modules:
  - from-file: common.yml
