---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: vedaos-next
description: This is my personal OS image.
base-image: quay.io/fedora/fedora-bootc
image-version: 43

modules:
  # install fedora logos before doing anything else for the time being,
  # otherwise aurora-logos would be installed instead for some reason
  - type: dnf
    install:
      packages:
        - fedora-logos

  # copying system files over to the system
  - type: files
    files:
      - source: system
        destination: /

  # a bit stripped down replica of ublue's base image
  - from-file: common/base.yml

  # install brew. updates would be handled with uupd
  - type: brew
    brew-analytics: false
    auto-update: false
    auto-upgrade: false

  # copy over nvidia-open akmods to the image for the next step
  - type: copy
    from: ghcr.io/ublue-os/akmods-nvidia-open:main-43-x86_64
    src: /rpms
    dest: /tmp/akmods-nv-rpms

  # install nvidia drivers using ublue script and their akmods
  # we will need to eventually do it on our own, but for the time being that's good enough
  - type: script
    snippets:
      - "curl -sSL --retry 3 -Lo /tmp/nvidia-install.sh https://github.com/ublue-os/main/raw/refs/heads/main/build_files/nvidia-install.sh"
      - "chmod +x /tmp/nvidia-install.sh"
      - "AKMODNV_PATH=/tmp/akmods-nv-rpms IMAGE_NAME='vedaos-next' /tmp/nvidia-install.sh"
      - "rm -rf /tmp/{akmods-nv-rpms,nvidia-install.sh}"

  # install gnome and a few things
  # took it from bluefin lts and zirconium :)
  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/packages
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      packages:
        - input-remapper
        - flatpak
        - tailscale
        - NetworkManager-adsl
        - f43-backgrounds-gnome
        - gdm
        - gnome-bluetooth
        - gnome-color-manager
        - gnome-control-center
        - gnome-initial-setup
        - gnome-remote-desktop
        - gnome-session-wayland-session
        - gnome-settings-daemon
        - gnome-shell
        - gnome-user-docs
        - gvfs-fuse
        - gvfs-goa
        - gvfs-gphoto2
        - gvfs-mtp
        - gvfs-smb
        - libsane-hpaio
        - nautilus
        - orca
        - ptyxis
        - sane-backends-drivers-scanners
        - xdg-desktop-portal-gnome
        - xdg-user-dirs-gtk
        - yelp-tools
        - plymouth
        - plymouth-system-theme
        - systemd-container
        - libcamera-v4l2
        - NetworkManager-wifi
        - atheros-firmware
        - brcmfmac-firmware
        - iwlegacy-firmware
        - iwlwifi-dvm-firmware
        - iwlwifi-mvm-firmware
        - mt7xxx-firmware
        - nxpwireless-firmware
        - realtek-firmware
        - tiwilink-firmware
        - alsa-firmware
        - alsa-sof-firmware
        - alsa-tools-firmware
        - intel-audio-firmware
        - gnome-disk-utility
        - uupd

  # remove some leftovers
  - type: dnf
    remove:
      packages:
        - console-login-helper-messages
        - gnome-tour

  # install gnome extensions
  - type: gnome-extensions
    install:
      - 19 # User Themes
      - 517 # Caffeine
      - 615 # AppIndicator Support
      - 3193 # Blue my Shell

  # add gschema overrides
  - type: gschema-overrides
    include:
      - zz0-extensions.gschema.override # enable installed extensions

  # install docker and some dev tools
  - type: dnf
    repos:
      cleanup: true
      files:
        - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      packages:
        - repo: docker-ce-stable
          packages:
            - docker-ce
            - docker-ce-cli
            - docker-compose-plugin
        - libcgroup
        - foundry
        - git

  # install steam
  - type: dnf
    install:
      install-weak-deps: false
      packages:
        - steam

  # set new os-release values
  - type: os-release
    properties:
      ID: vedaos
      ID_LIKE: fedora
      NAME: VedaOS
      PRETTY_NAME: VedaOS 43
      DEFAULT_HOSTNAME: vedaos

  # add flathub, a way better flatpak repo, and kill fedora flatpaks
  - type: script 
    snippets:
      - "mkdir -p /etc/flatpak/remotes.d/"
      - "curl --retry 3 -Lo /etc/flatpak/remotes.d/flathub.flatpakrepo https://dl.flathub.org/repo/flathub.flatpakrepo"
      - "rm -rf /usr/lib/systemd/system/flatpak-add-fedora-repos.service"

  # some finishing touches
  - type: script
    snippets:
      - "sed -i 's|uupd|& --disable-module-distrobox|' /usr/lib/systemd/system/uupd.service"
      - "ln -s /usr/libexec/docker/cli-plugins/docker-compose /usr/bin/docker-compose"
      - "mkdir -p /usr/lib/sysctl.d"
      - "echo 'net.ipv4.ip_forward = 1' >/usr/lib/sysctl.d/docker-ce.conf"
      - "sed -i 's/enable docker/disable docker/' /usr/lib/systemd/system-preset/90-default.preset"
      - "systemctl preset docker.service docker.socket"
      - "sed -i '/^REDHAT_BUGZILLA_PRODUCT=/d;/^REDHAT_BUGZILLA_PRODUCT_VERSION=/d;/^REDHAT_SUPPORT_PRODUCT=/d;/^REDHAT_SUPPORT_PRODUCT_VERSION=/d' /usr/lib/os-release"
      - "echo 'Hidden=true' >> /usr/share/applications/htop.desktop"
      - "echo 'Hidden=true' >> /usr/share/applications/nvtop.desktop"
      - "echo 'Hidden=true' >> /usr/share/applications/nvidia-settings.desktop"
      - "dnf5 versionlock clear"

  # enable systemd services
  - type: systemd
    system:
      enabled:
        - gdm.service
        - systemd-timesyncd
        - systemd-resolved.service
        - tailscaled.service
        - uupd.timer
        - flatpak-add-flathub-repos.service
      masked:
        - bootc-fetch-apply-updates.timer
        - bootc-fetch-apply-updates.service

  - type: initramfs

  - type: signing
