---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: vedaos
description: Opinionated custom image with Steam, GNOME and minimum installed packages, based on fedora-bootc.
base-image: quay.io/fedora/fedora-bootc
image-version: 43

modules:
  # install fedora logos and dnf5-plugins that is needed for copr management and other actions
  - type: dnf
    install:
      packages:
        - fedora-logos
        - dnf5-plugins

  # copying system files over to the system
  - type: files
    files:
      - source: system
        destination: /

  # remove leftovers from fedora-bootc
  - type: dnf
    remove:
      packages:
        - console-login-helper-messages
        - chrony
        - sssd*
        - qemu-user-static*
        - toolbox

  # delete chsh since we don't need it, create roothome dir, add fedora-multimedia
  - type: script
    snippets:
      - "rm -f /usr/bin/chsh"
      - "rm -f /usr/bin/lchsh"
      - "mkdir -p /var/roothome"
      - "dnf5 config-manager addrepo --from-repofile='https://negativo17.org/repos/fedora-multimedia.repo'"
      - "dnf5 config-manager setopt fedora-multimedia.priority=90"
      - "dnf5 config-manager setopt fedora-cisco-openh264.enabled=0"
  
  # install packages from fedora-multimedia, install ocl-icd
  - type: dnf
    install:
      skip-unavailable: true
      packages:
        - intel-gmmlib
        - intel-mediasdk
        - intel-vpl-gpu-rt
        - libheif
        - libva
        - libva-intel-media-driver
        - mesa-dri-drivers
        - mesa-filesystem
        - mesa-libEGL
        - mesa-libGL
        - mesa-libgbm
        - mesa-va-drivers
        - mesa-vulkan-drivers
        - ocl-icd

  # lock rpms from fedora-multimedia
  - type: script
    snippets:
      - "dnf5 versionlock add intel-gmmlib intel-mediasdk intel-vpl-gpu-rt libheif libva libva-intel-media-driver mesa-dri-drivers mesa-filesystem mesa-libEGL mesa-libGL mesa-libgbm mesa-va-drivers mesa-vulkan-drivers"

  # install so called "batteries" coined by ublue
  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/packages
        - ublue-os/staging
    install:
      packages:
        - ublue-os-luks
        - ublue-os-udev-rules
        - fedora-repos-archive
        - zstd
        - alsa-firmware
        - apr
        - apr-util
        - distrobox
        - fdk-aac
        - ffmpeg
        - ffmpeg-libs
        - ffmpegthumbnailer
        - flatpak-spawn
        - fuse
        - fzf
        - google-noto-sans-balinese-fonts
        - google-noto-sans-cjk-fonts
        - google-noto-sans-javanese-fonts
        - google-noto-sans-sundanese-fonts
        - grub2-tools-extra
        - heif-pixbuf-loader
        - htop
        - intel-vaapi-driver
        - just
        - libavcodec
        - libcamera
        - libcamera-gstreamer
        - libcamera-ipa
        - libheif
        - libcamera-tools
        - libfdk-aac
        - libimobiledevice-utils
        - libratbag-ratbagd
        - libva-utils
        - lshw
        - net-tools
        - nvme-cli
        - nvtop
        - openrgb-udev-rules
        - openssl
        - oversteer-udev
        - pam-u2f
        - pam_yubico
        - pamu2fcfg
        - pipewire-plugin-libcamera
        - powerstat
        - smartmontools
        - solaar-udev
        - squashfs-tools
        - symlinks
        - tcpdump
        - tmux
        - traceroute
        - usbmuxd
        - vim
        - wireguard-tools
        - wl-clipboard
        - xhost
        - xorg-x11-xauth
        - yubikey-manager

  # install cosign directly from github, use CoreOS' generator for emergency/rescue boot, bunch of workarounds
  - type: script
    scripts:
      - install-cosign.sh
      - fix-brew.sh # we're doing it here so it won't error out in snippets
    snippets:
      - "curl --retry 3 -sSLo /usr/lib/systemd/system-generators/coreos-sulogin-force-generator https://raw.githubusercontent.com/coreos/fedora-coreos-config/refs/heads/stable/overlay.d/05core/usr/lib/systemd/system-generators/coreos-sulogin-force-generator"
      - "chmod +x /usr/lib/systemd/system-generators/coreos-sulogin-force-generator"
      - "mv '/usr/share/doc/just/README.中文.md' '/usr/share/doc/just/README.zh-cn.md'"
      - "ln -s '/usr/share/fonts/google-noto-sans-cjk-fonts' '/usr/share/fonts/noto-cjk'"

  # swap kernel and install nvidia drivers and kmod
  - type: script
    scripts:
      - swap-kernel.sh
      - install-nvidia.sh

  # install brew. updates would be handled with uupd
  - type: copy
    from: ghcr.io/ublue-os/brew:latest
    src: /system_files
    dest: /

  # install gnome and a few things
  # took it from bluefin lts and zirconium :)
  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/packages
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      packages:
        - input-remapper
        - flatpak
        - tailscale
        - NetworkManager-adsl
        - gdm
        - gnome-bluetooth
        - gnome-color-manager
        - gnome-control-center
        - gnome-remote-desktop
        - gnome-session-wayland-session
        - gnome-settings-daemon
        - gnome-shell
        - gnome-user-docs
        - gvfs-fuse
        - gvfs-goa
        - gvfs-gphoto2
        - gvfs-mtp
        - gvfs-smb
        - libsane-hpaio
        - nautilus
        - orca
        - ptyxis
        - sane-backends-drivers-scanners
        - xdg-desktop-portal-gnome
        - xdg-user-dirs-gtk
        - yelp-tools
        - plymouth
        - plymouth-system-theme
        - systemd-container
        - libcamera-v4l2
        - NetworkManager-wifi
        - atheros-firmware
        - brcmfmac-firmware
        - iwlegacy-firmware
        - iwlwifi-dvm-firmware
        - iwlwifi-mvm-firmware
        - mt7xxx-firmware
        - nxpwireless-firmware
        - realtek-firmware
        - tiwilink-firmware
        - alsa-firmware
        - alsa-sof-firmware
        - alsa-tools-firmware
        - intel-audio-firmware
        - gnome-disk-utility
        - uupd
        - unzip
        - adw-gtk3-theme
        - glibc-all-langpacks
        - wget
        - jetbrains-mono-fonts-all
        - fuse-libs
        - squashfuse-libs
        - glycin-thumbnailer
        - fira-code-fonts
        - hyfetch
        - fastfetch
        - jmtpfs
        - NetworkManager-config-connectivity-fedora
        - NetworkManager-openvpn
        - NetworkManager-wwan
        - cups
        - fprintd
        - fprintd-pam
        - hplip
        - hyperv-daemons
        - ibus
        - libratbag-ratbagd
        - open-vm-tools
        - open-vm-tools-desktop
        - pcsc-lite
        - qemu-guest-agent
        - systemd-oomd-defaults
        - whois
        - wireguard-tools
        - zram-generator-defaults
      exclude:
        - gnome-tour
      
  # adding terra just to install nerd fonts
  - type: script
    snippets:
      - "dnf5 -y install --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release"
      - "dnf5 -y install jetbrainsmono-nerd-fonts"
      - "dnf5 -y remove terra-release"
      - "rm -rf /etc/yum.repos.d/terra*"

  # install some backgrounds
  - type: dnf
    repos:
      cleanup: true
      copr:
        - bazzite-org/bazzite
    install:
      packages:
        - f43-backgrounds-gnome
        - gnome-backgrounds
        - steamdeck-backgrounds

  # install gnome extensions
  - type: gnome-extensions
    install:
      - 19 # User Themes
      - 517 # Caffeine
      - 615 # AppIndicator Support
      - 3193 # Blur my Shell
      - 4222 # Hot Edge
      - 4269 # Alphabetical App Grid
      - 5105 # RebootToUEFI
      - 7535 # Accent Icons
      - 8084 # adw-gtk3 Colorizer

  # add gschema overrides
  - type: gschema-overrides
    include:
      - zz0-vedaos.gschema.override

  # install some dev tools
  - type: dnf
    install:
      packages:
        - foundry
        - git
        - podman-compose
        - flatpak-builder

  # install steam
  - type: dnf
    install:
      install-weak-deps: false
      packages:
        - steam

  # give bazzite copr repos a priority, install gamescope
  - type: script
    snippets:
      - "dnf5 -y copr enable bazzite-org/bazzite"
      - "dnf5 -y copr enable bazzite-org/bazzite-multilib"
      - "dnf5 -y config-manager setopt '*bazzite*'.priority=90"
      - "dnf5 -y install gamescope-libs gamescope-shaders"
      - "dnf5 -y copr disable bazzite-org/bazzite"
      - "dnf5 -y copr disable bazzite-org/bazzite-multilib"

  # set new os-release values
  - type: os-release
    properties:
      ID: vedaos
      ID_LIKE: fedora
      NAME: VedaOS
      PRETTY_NAME: VedaOS 43
      DEFAULT_HOSTNAME: vedaos
      VERSION_CODENAME: Next
      HOME_URL: https://lumaeris.com/vedaos
      DOCUMENTATION_URL: https://lumaeris.com/vedaos
      SUPPORT_URL: https://github.com/Lumaeris/vedaos/issues
      BUG_REPORT_URL: https://github.com/Lumaeris/vedaos/issues

  # add flathub, a way better flatpak repo, and remove fedora flatpaks
  - type: script 
    snippets:
      - "mkdir -p /etc/flatpak/remotes.d/"
      - "curl --retry 3 -Lo /etc/flatpak/remotes.d/flathub.flatpakrepo https://dl.flathub.org/repo/flathub.flatpakrepo"
      - "rm -f /usr/lib/systemd/system/flatpak-add-fedora-repos.service"

  # some finishing touches
  - type: script
    scripts:
      - install-morewaita.sh
    snippets:
      - "sed -i 's|uupd|& --disable-module-distrobox|' /usr/lib/systemd/system/uupd.service"
      - "sed -i '/^REDHAT_BUGZILLA_PRODUCT=/d;/^REDHAT_BUGZILLA_PRODUCT_VERSION=/d;/^REDHAT_SUPPORT_PRODUCT=/d;/^REDHAT_SUPPORT_PRODUCT_VERSION=/d;/^SUPPORT_END=/d' /usr/lib/os-release"
      - "echo 'Hidden=true' >> /usr/share/applications/htop.desktop"
      - "echo 'Hidden=true' >> /usr/share/applications/nvtop.desktop"
      - "echo 'Hidden=true' >> /usr/share/applications/nvidia-settings.desktop"
      - "mkdir -p /usr/lib/extest"
      - "curl --retry 3 -Lo /usr/lib/extest/libextest.so https://github.com/bazzite-org/extest/releases/latest/download/libextest.so"
      - "curl --retry 3 -Lo /usr/bin/winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks"
      - "chmod +x /usr/bin/winetricks"
      - "sed -i 's@/usr/bin/steam@/usr/bin/vedaos-steam@g' /usr/share/applications/steam.desktop"
      - "rm -rf /usr/share/doc"
      - "rm -rf /usr/src"
      - "rpm --erase --nodeps kernel-cachyos-devel akmod-nvidia"
      - "echo 'HOMEBREW_NO_ANALYTICS=1' >> /etc/environment"
      - "dnf5 versionlock clear"
      - "dnf5 clean all"

  # enable systemd services
  - type: systemd
    system:
      enabled:
        - gdm.service
        - systemd-timesyncd.service
        - systemd-resolved.service
        - tailscaled.service
        - uupd.timer
        - flatpak-add-flathub-repos.service
        - input-remapper.service
        - rechunker-group-fix.service
        - nvctk-cdi.service
        - brew-setup.service
      disabled:
        - bootc-fetch-apply-updates.timer
        - bootc-fetch-apply-updates.service
        - akmods-keygen@akmods-keygen.service
        - akmods-keygen.target
        - rpm-ostree-countme.timer
      masked:
        - bootc-fetch-apply-updates.timer
        - bootc-fetch-apply-updates.service
        - akmods-keygen@akmods-keygen.service
        - akmods-keygen.target
    user:
      enabled:
        - bazaar.service

  - type: initramfs

  - type: signing
